ConfigFile = '/home/markas/.config/lazysql/config.toml'

[application]
DefaultPageSize = 300
DisableSidebar = false
SidebarOverlay = false
MaxQueryHistoryPerConnection = 100

[[database]]
Name = 'localhost'
URL = 'postgresql://sail:password@localhost/laravel?sslmode=disable'
Provider = 'postgres'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = 'laravel'
URLParams = ''
ReadOnly = false
Commands = []

[[database]]
Name = 'BrainArena'
URL = 'postgres://brain:arena@localhost:5432/brain_arena?sslmode=disable'
Provider = 'postgres'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = 'brain_arena'
URLParams = ''
ReadOnly = false
Commands = []
